version: "3"
services:
  client:
    build: ./client
    env_file:
      - .env
    ports:
      - "4000:80"

  server:
    depends_on:
      - db
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/server
      - /usr/src/server/node_modules

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:80"

volumes:
  db_data: {}
